### PR TITLE
Find class module by Module.safe_concat/1

### PR DESCRIPTION
**Pull request by zhongwencool**
if just use String.to_existing_atom/1
```
%Verk.Job{class: ModuleAtom.Name}
will be change to 
"Elixir.Elixir.ModuleAtom.Name" |> String.to_existing_atom
```
so we better use Module.safe_concat/1 to add Elixir prefix 

：）
Thanks for the great project~

### CODE REVIEW

**Comment by edgurgel** [comment]
Thanks! Could you rebase with master and add a test? Cheers!

**Comment by zhongwencool** [comment]
done~ @edgurgel

**Comment by edgurgel** [comment]
Did you rebase with verk's origin master? Cause here it says:

> This branch has conflicts that must be resolved

**Comment by edgurgel** [comment]
Awesome! Thank you very much! 👍

**Pull request merged**
