### PR TITLE
Upgrade Timex to 2.1.4.

### PR DESCRIPTION
**Pull request by krasio**
Upgrade Timex, fix failing tests and update some code to remove warnings.

### CODE REVIEW

**Comment by veverkap** [comment]
This is awesome!  :+1:

**Comment by edgurgel** [comment]
Thank you! I will check this today! :+1:

**Comment by edgurgel** [comment]
LGTM but I would change one thing. Remove those `Tzdata.App.start` calls and simply make the `:tzdata` available through the `test_helper.exs`. Just add this line to the `test_helper`:

`{ :ok, _ } = Application.ensure_all_started(:tzdata)`

Usually we use the `Application` module to start the app instead of using a custom function from the project :+1:

**Comment by krasio** [comment]
Thanks, I was sure there is a better way to do this :). Updated.

**Comment by edgurgel** [comment]
Awesome!

**Comment by edgurgel** [comment]
:tada:

**Pull request merged**
