### PR TITLE
Allow custom functions to be called

### PR DESCRIPTION
**Pull request by mkaszubowski**

### CODE REVIEW

**Comment by immon** [comment]
You can have many `perform` functions in the worker module. Then you can use pattern matching or guards clauses to run a function you want.
```elixir
defmodule MyApp.Worker do
  def perform("A", arg1, arg2), do: :timer.sleep(1_000)
  def perform("B", arg1, arg2), do: :timer.sleep(2_000)
end
``` 
And then to match the first definition you run
```elixir
Verk.enqueue %Verk.Job{class: Worker, queue: :default, arg: ["A", 1, 2]}
```

Would it work for you?

**Comment by edgurgel** [comment]
Oops somehow I missed this PR. Hm I'm not sure what we gain in terms of feature if we support this option...

I actually like the idea of having a specific module to do "work" so that the user actually thought about writing a worker that will work on something that is "idempotent" and can be retried etc.

What do you all think?

**Comment by mkaszubowski** [comment]
@immon  I was actually thinking of using the existing modules without having to change the interface. But I think @edgurgel has a point: it's better to wrap the existing module/function in "worker" module which will immediately reveal its intention. 

Having said that, I guess we can close this one. Thanks for the discussion and sharing your thoughts :)

**Comment by edgurgel** [comment]
Cool! Thanks anyway for the PR!

**Pull request closed without merging**
