### PR TITLE
Remove GenEvent

### PR DESCRIPTION
**Pull request by edgurgel**
Removing GenEvent and using GenStage to produce events. Still unsure if we should discard the demand and simply broadcast... 🤔

### CODE REVIEW

**Comment by mitchellhenke** [comment]
😀 

@edgurgel Biggest worry for me would be storing a large amount of events that may never be sent.

**Comment by edgurgel** [comment]
@mitchellhenke yeah we would need to have a way to drop old events if we are not processing them properly. That's why I'm still wondering if it's worth thinking about this now.

**Comment by mitchellhenke** [comment]
@edgurgel could store a small number by default and make it configurable?

**Comment by edgurgel** [comment]
Yeah probably!

**Pull request merged**
