### PR TITLE
feat(mix deps) allow Timex 3

### PR DESCRIPTION
**Pull request by rmosolgo**
Hi, thanks for your work on this project! 

I'm trying to use it in a Phoenix app but I got a dependency error: 

```
~/code/helpdesk $ mix deps.get
Running dependency resolution

Failed to use "timex" because
  verk (versions 0.12.0 and 0.12.1) requires ~> 2.0
  Locked to 3.0.8 in your mix.lock

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

So I thought I'd try to update it myself. The old version of `combine` had this error: 

```
~/code/verk $ mix test
==> combine
Compiling 6 files (.ex)

== Compilation error on file lib/combine/parsers/text.ex ==
** (CompileError) Elixir.Combine.Parsers.Text: function float_impl/1+43:
  Internal consistency check failed - please report this bug.
  Instruction: {call,4,{f,129}}
  Error:       {multiple_match_contexts,[{x,0},1]}:

    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

([open issue on combine](https://github.com/bitwalker/combine/issues/17))

So I updated that, too. Right now, I'm getting one failure, which I also get on master (with the updated `combine`): 

```
~/code/verk $ mix test
warning: variable job is unused
  test/worker_test.exs:71

..........................................................................

  1) test call dequeue and timeout (Verk.QueueManagerTest)
     test/queue_manager_test.exs:104
     ** (exit) exited in: GenServer.call(#PID<0.857.0>, {:dequeue, 1}, 1)
         ** (EXIT) process attempted to call itself
     stacktrace:
       (elixir) lib/gen_server.ex:598: GenServer.call/3
       (verk) lib/verk/queue_manager.ex:46: Verk.QueueManager.dequeue/3
       test/queue_manager_test.exs:105: (test)

...........................................................

Finished in 4.6 seconds
134 tests, 1 failure

Randomized with seed 284297
```

How is this patch? Is that error failing already?

### CODE REVIEW

**Comment by edgurgel** [comment]
I'm keen to bump to Timex 3! Thanks for starting this PR. I will check this later today!

**Comment by karmajunkie** [comment]
+1 on the need to support Timex 3, running into the same problem, but with this branch I get the following:

```
==> verk
Compiling 20 files (.ex)

== Compilation error on file lib/verk.ex ==
** (CompileError) lib/verk.ex:70: Timex.DateTime.__struct__/0 is undefined, cannot expand struct Timex.DateTime
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
```

**Comment by rmosolgo** [comment]
I had the same issue when I tried to run this in my app, I guess it's not quite compatible :S I don't mind giving it a try, but I might not get to it til next week, so if someone else wants to do it, go to town!!

**Comment by karmajunkie** [comment]
I'm getting a test failure out of the box in the queue manager test:

```
 1) test call dequeue and timeout (Verk.QueueManagerTest)
     test/queue_manager_test.exs:104
     ** (exit) exited in: GenServer.call(#PID<0.1359.0>, {:dequeue, 1}, 1)
         ** (EXIT) process attempted to call itself
     stacktrace:
       (elixir) lib/gen_server.ex:598: GenServer.call/3
       (verk) /Users/keith/bidlily/verk/lib/verk/queue_manager.ex:46: Verk.QueueManager.dequeue/3
       test/queue_manager_test.exs:105: (test)
```

Is this a known failure? I don't want to spend time on it right this second if so—just looking at the test it seems flawed, and I can't tell if its a placeholder or changed behavior.

**Comment by edgurgel** [comment]
This doesn't seem to be related to Timex but with Elixir 1.3. I will push a fix later today.

We still need to see which changes on Timex may affect Verk.

**Comment by edgurgel** [comment]
Done. Can you update with current master and try running with Timex 3? Tests are passing on Travis

**Comment by karmajunkie** [comment]
your master is working for me now... i'm working off @rmosolgo's timex-3 branch so will rebase into there.

**Comment by edgurgel** [comment]
Awesome

**Comment by karmajunkie** [comment]
@edgurgel i've got a branch with mostly passing tests updated to Timex 3. The tests in `test/schedule_manager_test.exs` are a little brittle from the mocking thats going on in there, and they're my last 6 that need to pass. would you object some bigger changes in that file?

**Comment by rmosolgo** [comment]
Sorry I haven't been able to come back to this, I see that work is being continued in #78 !

**Pull request closed without merging**
