### PR TITLE
Limit stacktrace size when job fails to configured limit

### PR DESCRIPTION
**Pull request by krasio**
Here's something to implement #21. Not sure how to test it though 😞.

### CODE REVIEW

**Comment by edgurgel** [comment]
I think that's pretty much it for the implementation. I would probably call `handle_call(:retry, ..)` with a fake stacktrace similar to this one: https://github.com/edgurgel/raygun/blob/67c858dad1063d33c01cfb1fe7cbba95aeebf9cb/test/format_test.exs#L9-L14

What do you think?

**Comment by krasio** [comment]
The best I can think of is something like https://github.com/krasio/verk/commit/6f4ce3f190b755312375c1e111a084f3d3a87a5b. I don't like it though, it's too much testing the implementation (pretty much duplicate it in the tests) than the behaviour. On the other hand ugly test might be better than no test at all  ¯\_(ツ)_/¯.

**Comment by edgurgel** [comment]
I think that's good enough for now. When and if we extract this part of the code somewhere else we can refactor and remove this "ugly" test. LGTM :)

**Comment by krasio** [comment]
OK, merge and rebased.

**Comment by edgurgel** [comment]
Amazing! 🎉 ❤️

**Pull request merged**
