### PR TITLE
Add [SortedSet,RetrySet].requeue_job for on-demand job retries

### PR DESCRIPTION
**Pull request by keyan**
This PR is a first pass at adding the necessary Verk changes required to support on-demand job retrying for jobs in the retry queue (see: https://github.com/edgurgel/verk_web/issues/11).

The implementation is fairly self-explanatory, it primarily follows the patterns used in [enqueue_retriable_job.lua](https://github.com/edgurgel/verk/blob/master/priv/enqueue_retriable_job.lua) as well as [SortedSet.delete](https://github.com/edgurgel/verk/blob/c252802a095efe786c48299898b1f249d8108064/lib/verk/sorted_set.ex#L109-L114).

I expect that the change for https://github.com/edgurgel/verk_web/issues/11 will simply be the addition of another button (as for "Delete") that calls `RetrySet.requeue_job` in the controller ([as for "Delete"](https://github.com/edgurgel/verk_web/blob/bc0d71888944b1490e49a5a051f5711b65a66a49/web/controllers/retries_controller.ex#L18-L24)).

Not sure about the implementation so let me know your thoughts!

### CODE REVIEW

**Comment by keyan** [comment]
Huh, looks like this is failing because the script isn't being loaded into Redis. This should be happening at compile time IIRC. Perhaps you have resolved this before Ed?

**Comment by edgurgel** [comment]
Thanks once again for another awesome contribution! I will have a look later today but it should be pretty simple to fix this build failure. The code looks great 👍

**Comment by edgurgel** [comment]
I think the only missing piece here is to stub the EVALSHA command. The idea is that the script was tested standalone (as part of the Scripts module) so just do like this: 

https://github.com/edgurgel/verk/blob/master/test/queue_manager_test.exs#L58-L66

Test if the right arguments are being passed.

What do you think?

**Comment by keyan** [comment]
Added the script stubbing tests as discussed above. Also, I realized I wasn't testing the no-op case, so I added tests for that and also fixed the lua script to return `nil` in those cases (it should have already been doing this).

This is passing locally, still not sure why this is behaving differently on Travis and not loading the script into Redis.

**Comment by edgurgel** [comment]
I will pull your branch and check now! Thanks!

**Comment by keyan** [comment]
Also I'd like to rebase 03901ba and a42d9d8 at some point, but I kept them for clarity for now.

**Comment by edgurgel** [comment]
Cool that's ok!

**Comment by keyan** [comment]
I addressed your point about stubbing all Redis calls in `SortedSet` tests, makes sense 👍 

The commit history was getting messy so I rebased. Seems that Travis is picking up the new script now? Did you change something?

**Comment by edgurgel** [comment]
I didn't change a thing! Anyway I'm merging and soon releasing it so we can use for the verk web retry button <3

**Pull request merged**
